enum DISCS_ACTIONS {
    FETCH_DISCS_REQUEST = 'DISCS--FETCH_DISCS_REQUEST',
    FETCH_DISCS_SUCCESS = 'DISCS--FETCH_DISCS_SUCCESS',
    FETCH_DISCS_ERROR = 'DISCS--FETCH_DISCS_ERROR',
}

export default DISCS_ACTIONS;
