enum STORE_ACTIONS {
    FETCH_ITEMS_REQUEST = 'STORE--FETCH_ITEMS_REQUEST',
    FETCH_ITEMS_SUCCESS = 'STORE--FETCH_ITEMS_SUCCESS',
    FETCH_ITEMS_ERROR = 'STORE--FETCH_ITEMS_ERROR',
    FETCH_CART_REQUEST = 'STORE--FETCH_CART_REQUEST',
    FETCH_CART_SUCCESS = 'STORE--FETCH_CART_SUCCESS',
    FETCH_CART_ERROR = 'STORE--FETCH_CART_ERROR',
    ADD_ITEM_TO_CART = 'STORE--ADD_ITEM_TO_CART',
    REMOVE_ITEM_FROM_CART = 'STORE--REMOVE_ITEM_FROM_CART',
}

export default STORE_ACTIONS;
