enum STORE_ACTIONS {
    ADD_TO_CART = 'STORE--ADD_TO_CART',
    REMOVE_FROM_CART = 'STORE--REMOVE_FROM_CART',
    FETCH_ITEMS_REQUEST = 'STORE--FETCH_ITEMS_REQUEST',
    FETCH_ITEMS_SUCCESS = 'STORE--FETCH_ITEMS_SUCCESS',
    FETCH_ITEMS_ERROR = 'STORE--FETCH_ITEMS_ERROR',
}

export default STORE_ACTIONS;
