enum PRESS_ACTIONS {
    FETCH_ACCLAIMS_REQUEST = 'PRESS--FETCH_ACCLAIMS_REQUEST',
    FETCH_ACCLAIMS_SUCCESS = 'PRESS--FETCH_ACCLAIMS_SUCCESS',
    FETCH_ACCLAIMS_ERROR = 'PRESS--FETCH_ACCLAIMS_ERROR',
    OTHER_ACTION = 'PRESS--OTHER_ACTION',
}

export default PRESS_ACTIONS;
