enum AUDIO_ACTIONS {
    IS_HOVER_SEEKRING = 'AUDIO_ACTIONS--IS_HOVER_SEEKRING',
    IS_HOVER_PLAYPAUSE = 'AUDIO_ACTIONS--IS_HOVER_PLAYPAUSE',
    IS_MOUSE_MOVE = 'AUDIO_ACTIONS--IS_MOUSE_MOVE',
    FETCH_PLAYLIST_REQUEST = 'AUDIO_ACTIONS--FETCH_PLAYLIST_REQUEST',
    FETCH_PLAYLIST_SUCCESS = 'AUDIO_ACTIONS--FETCH_PLAYLIST_SUCCESS',
    FETCH_PLAYLIST_ERROR = 'AUDIO_ACTIONS--FETCH_PLAYLIST_ERROR',
    OTHER_ACTIONS = 'AUDIO_ACTIONS--OTHER_ACTIONS',
}

export default AUDIO_ACTIONS;
