enum STORE_ACTIONS {
    ADD_TO_CART = 'STORE--ADD_TO_CART',
    REMOVE_FROM_CART = 'STORE--REMOVE_FROM_CART',
    CHECKOUT_SUBMIT = 'STORE--CHECKOUT_SUBMIT',
    CHECKOUT_SUCCESS = 'STORE--CHECKOUT_SUCCESS',
    CHECKOUT_FAILURE = 'STORE--CHECKOUT_FAILURE',
    FETCH_ITEMS_REQUEST = 'STORE--FETCH_ITEMS_REQUEST',
    FETCH_ITEMS_SUCCESS = 'STORE--FETCH_ITEMS_SUCCESS',
    FETCH_ITEMS_ERROR = 'STORE--FETCH_ITEMS_ERROR',
    INIT_CART_SUCCESS = 'STORE--INIT_CART_SUCCESS',
    INIT_CART_ERROR = 'STORE--INIT_CART_ERROR',
    ADD_ITEM_TO_CART = 'STORE--ADD_ITEM_TO_CART',
    REMOVE_ITEM_FROM_CART = 'STORE--REMOVE_ITEM_FROM_CART',
}

export default STORE_ACTIONS;
