enum STORE_ACTIONS {
    ADD_TO_CART = 'STORE--ADD_TO_CART',
    REMOVE_FROM_CART = 'STORE--REMOVE_FROM_CART',
    FETCH_ITEMS_REQUEST = 'STORE--FETCH_ITEMS_REQUEST',
    FETCH_ITEMS_SUCCESS = 'STORE--FETCH_ITEMS_SUCCESS',
    FETCH_ITEMS_ERROR = 'STORE--FETCH_ITEMS_ERROR',
    INIT_CART_SUCCESS = 'STORE--INIT_CART_SUCCESS',
    INIT_CART_ERROR = 'STORE--INIT_CART_ERROR',
    CHECKOUT_REQUEST = 'STORE--CHECKOUT_REQUEST',
    CHECKOUT_ERROR = 'STORE--CHECKOUT_ERROR',
    CHECKOUT_SUCCESS = 'STORE--CHECKOUT_SUCCESS',
}

export default STORE_ACTIONS;
