enum STORE_ACTIONS {
    FETCH_ITEMS_REQUEST = 'STORE--FETCH_ITEMS_REQUEST',
    FETCH_ITEMS_SUCCESS = 'STORE--FETCH_ITEMS_SUCCESS',
    FETCH_ITEMS_ERROR = 'STORE--FETCH_ITEMS_ERROR',
}

export default STORE_ACTIONS;
