enum NAV_ACTIONS {
    NAV_TOGGLE_SUBNAV = 'NAV_ACTIONS--TOGGLE_SUBNAV',
    NAV_TOGGLE_NAV = 'NAV_ACTIONS--TOGGLE_NAV',
    NAV_TOGGLE_EXPANDED = 'NAV_ACTIONS--TOGGLE_EXPANDED',
    NAV_SET_ONSCROLL = 'NAV_ACTIONS--SET_ONSCROLL',
    NAV_LAST_SCROLL = 'NAV_ACTIONS--LAST_SCROLL',
    NAV_OTHER_ACTIONS = 'NAV_ACTIONS--OTHER_ACTIONS',
}

export default NAV_ACTIONS;
