enum VIDEO_ACTIONS {
    FETCH_PLAYLIST_SUCCESS = 'VIDEO--FETCH_PLAYLIST_SUCCESS',
    FETCH_PLAYLIST_REQUEST = 'VIDEO--FETCH_PLAYLIST_REQUEST',
    FETCH_PLAYLIST_ERROR = 'VIDEO--FETCH_PLAYLIST_ERROR',
    PLAYER_IS_READY = 'VIDEO--PLAYER_IS_READY',
    PLAY_ITEM = 'VIDEO--PLAY_ITEM',
    TOGGLE_PLAYLIST = 'VIDEO--TOGGLE_PLAYLIST',
    RESET_PLAYER = 'VIDEO--RESET_PLAYER',
    OTHER_ACTIONS = 'VIDEO--OTHER_ACTIONS',
}

export default VIDEO_ACTIONS;
