enum ADMIN_ACTIONS {
    EDIT_EVENT = 'ADMIN_SCHEDULE--EDIT_EVENT',
    UPDATE_DATE = 'ADMIN_SCHEDULE--UPDATE_DATE',
    UPDATE_TYPE = 'ADMIN_SCHEDULE--UPDATE_TYPE',
    UPDATE_NAME = 'ADMIN_SCHEDULE--UPDATE_NAME',
    UPDATE_LOCATION = 'ADMIN_SCHEDULE--UPDATE_LOCATION',
    UPDATE_TIME = 'ADMIN_SCHEDULE--UPDATE_TIME',
    UPDATE_PROGRAM = 'ADMIN_SCHEDULE--UPDATE_PROGRAM',
    UPDATE_COLLABORATORS = 'ADMIN_SCHEDULE--UPDATE_COLLABORATORS',
    UPDATE_NOTIME = 'ADMIN_SCHEDULE--UPDATE_NOTIME',
    UPDATE_WEBSITE = 'ADMIN_SCHEDULE--UPDATE_WEBSITE',
    GEOCODE_ERROR = 'ADMIN_SCHEDULE--GEOCODE_ERROR',
    FETCH_EVENTS_ERROR = 'ADMIN_SCHEDULE--FETCH_EVENTS_ERROR',
    FETCH_EVENTS_REQUEST = 'ADMIN_SCHEDULE--FETCH_EVENTS_REQUEST',
    FETCH_EVENTS_SUCCESS = 'ADMIN_SCHEDULE--FETCH_EVENTS_SUCCESS',
    OTHER_ACTION = 'ADMIN_SCHEDULE--OTHER_ACTION',
}

export default ADMIN_ACTIONS;
