enum PHOTO_ACTIONS {
    FETCH_PHOTOS_REQUEST = 'PHOTO_ACTIONS--FETCH_PHOTOS_REQUEST',
    FETCH_PHOTOS_SUCCESS = 'PHOTO_ACTIONS--FETCH_PHOTOS_SUCCESS',
    FETCH_PHOTOS_ERROR = 'PHOTO_ACTIONS--FETCH_PHOTOS_ERROR',
    SELECT_PHOTO = 'PHOTO_ACTIONS--SELECT_PHOTO',
    OTHER_ACTION = 'PHOTO_ACTIONS--OTHER_ACTION',
}

export default PHOTO_ACTIONS;
